import subprocess

# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_1", '0.3'])
# subprocess.Popen(["python", "run_simulations_AC_RF_Vaz_n_target.py", "sim_par_1", '0.3'])
subprocess.Popen(["python", "run_simulations_AC_LR_Vaz_n_target.py", "sim_par_1", '0.7'])
subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_1", '0.3'])

# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_1", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_1", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_2", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_2", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_3", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_target.py", "sim_par_3", '0.75'])

# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_1", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_1", '0.75'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_2", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_2", '0.75'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_3", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_target.py", "sim_par_3", '0.75'])

# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_1", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_1", '0.75'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_2", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_2", '0.75'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_3", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_target.py", "sim_par_3", '0.75'])

# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_1", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_1", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_2", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_2", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_3", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_LR_n_target.py", "sim_par_3", '0.75'])

# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_4", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_4", '0.75'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_5", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_5", '0.75'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_6", '0.25'])
# subprocess.Popen(["python", "run_simulations_rkhs_n_source_target.py", "sim_par_6", '0.75'])

# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_4", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_4", '0.75'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_5", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_5", '0.75'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_6", '0.25'])
# subprocess.Popen(["python", "run_simulations_Vaz_n_source_target.py", "sim_par_6", '0.75'])

# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_4", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_4", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_5", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_5", '0.75'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_6", '0.25'])
# subprocess.Popen(["python", "run_simulations_AC_RF_n_source_target.py", "sim_par_6", '0.75'])